"! Any kind of expression (function, operator, elementary value).
"! The class implementing a function has a name starting with ZCL_XLOM__EX_FU_
"! and it's instantiated by the method GET_EXPRESSION_FROM_FUNCTION of the class ZCL_XLOM__EX_UT_PARSER.
"! The class implementing an operator has a name starting with ZCL_XLOM__EX_OP_
"! and it's instantiated by the method GET_EXPRESSION_FROM_OPERATOR of the class ZCL_XLOM__EX_UT_PARSER.
"! The class implementing an elementary value has a name starting with ZCL_XLOM__EX_EL_
"! and it's instantiated by the method PARSE_EXPRESSION_4 of the class ZCL_XLOM__EX_UT_PARSER.
INTERFACE zif_xlom__ex
  PUBLIC.

  TYPES ty_expression_type TYPE i.
*  TYPES:
*    BEGIN OF ts_operand_result,
*      name                     TYPE string,
*      object                   TYPE REF TO zif_xlom__va,
*      "! <ul>
*      "! <li>'X': the argument isn't changed when the formula is expanded for Array Evaluation
*      "!          e.g. the argument Array of the function INDEX: if A1 contains =INDEX(C1:D2,&lcub;1,2&rcub;,&lcub;1,2&rcub;),
*      "!          A1 and B1 values are the same as if they contain =INDEX(C1:D2,1,1) and =INDEX(C1:D2,2,2).</li>
*      "! <li>' ': the argument is changed when the formula is expanded for Array Evaluation
*      "!          e.g.the argument Text of the function RIGHT: if A1 contains =RIGHT(A1:A2,&lcub;1;2&rcub;),
*      "!          A1 and A2 values are the same as if they contain =RIGHT(A1,1) and =RIGHT(A2,2).</li>
*      "! </ul>
*      not_part_of_result_array TYPE abap_bool,
*    END OF ts_operand_result.
*  TYPES tt_operand_result TYPE SORTED TABLE OF ts_operand_result WITH UNIQUE KEY name.
  TYPES tt_operand_result TYPE STANDARD TABLE OF REF TO zif_xlom__va WITH EMPTY KEY.
  TYPES:
    BEGIN OF ts_operand_expr,
      name                     TYPE string,
      object                   TYPE REF TO zif_xlom__ex,
      "! <ul>
      "! <li>'X': the argument isn't changed when the formula is expanded for Array Evaluation
      "!          e.g. the argument Array of the function INDEX: if A1 contains =INDEX(C1:D2,&lcub;1,2&rcub;,&lcub;1,2&rcub;),
      "!          A1 and B1 values are the same as if they contain =INDEX(C1:D2,1,1) and =INDEX(C1:D2,2,2).</li>
      "! <li>' ': the argument is changed when the formula is expanded for Array Evaluation
      "!          e.g.the argument Text of the function RIGHT: if A1 contains =RIGHT(A1:A2,&lcub;1;2&rcub;),
      "!          A1 and A2 values are the same as if they contain =RIGHT(A1,1) and =RIGHT(A2,2).</li>
      "! </ul>
      not_part_of_result_array TYPE abap_bool,
    END OF ts_operand_expr.
  TYPES tt_operand_expr TYPE SORTED TABLE OF ts_operand_expr WITH UNIQUE KEY name.
  TYPES tt_argument_or_operand TYPE STANDARD TABLE OF REF TO zif_xlom__ex WITH EMPTY KEY.
  TYPES:
    BEGIN OF ts_parameter,
      name                     TYPE string,
      "! If not bound, the parameter is mandatory. If bound, the parameter is optional.
      default                  TYPE REF TO zif_xlom__ex,
      not_part_of_result_array TYPE abap_bool,
    END OF ts_parameter.
  TYPES tt_parameter TYPE STANDARD TABLE OF ts_parameter WITH EMPTY KEY.

*  TYPES:
*    "! TO BE DELETED AS NOT USED ANYMORE BY ZCL_XLOM__EX_UT_EVAL
*    BEGIN OF ts_evaluate_array_operands,
*      result          TYPE REF TO zif_xlom__va,
*      operand_results TYPE tt_operand_result,
*    END OF ts_evaluate_array_operands.

  CONSTANTS:
    "! Used to replace IS INSTANCE OF, in case one day the code is backported to ABAP before 7.50.
    BEGIN OF c_type,
      array          TYPE ty_expression_type VALUE 1,
      boolean        TYPE ty_expression_type VALUE 2,
      empty_argument TYPE ty_expression_type VALUE 3,
      error          TYPE ty_expression_type VALUE 4,
      number         TYPE ty_expression_type VALUE 5,
      range          TYPE ty_expression_type VALUE 6,
      string         TYPE ty_expression_type VALUE 7,
      BEGIN OF operation,
        ampersand        TYPE ty_expression_type VALUE 100,
        colon            TYPE ty_expression_type VALUE 101,
        comma            TYPE ty_expression_type VALUE 102,
        divide           TYPE ty_expression_type VALUE 103,
        equal            TYPE ty_expression_type VALUE 104,
        exponent         TYPE ty_expression_type VALUE 105,
        greater          TYPE ty_expression_type VALUE 106,
        greater_or_equal TYPE ty_expression_type VALUE 107,
        lower            TYPE ty_expression_type VALUE 108,
        lower_or_equal   TYPE ty_expression_type VALUE 109,
        minus            TYPE ty_expression_type VALUE 110,
        minus_unary      TYPE ty_expression_type VALUE 111,
        mult             TYPE ty_expression_type VALUE 112,
        not_equal        TYPE ty_expression_type VALUE 113,
        percent          TYPE ty_expression_type VALUE 114,
        plus             TYPE ty_expression_type VALUE 115,
        plus_unary       TYPE ty_expression_type VALUE 116,
        space_           TYPE ty_expression_type VALUE 117,
      END OF operation,
      BEGIN OF function,
        abs                      TYPE ty_expression_type VALUE 1001,
        accrint                  TYPE ty_expression_type VALUE 1002,
        accrintm                 TYPE ty_expression_type VALUE 1003,
        acos                     TYPE ty_expression_type VALUE 1004,
        acosh                    TYPE ty_expression_type VALUE 1005,
        acot                     TYPE ty_expression_type VALUE 1006,
        acoth                    TYPE ty_expression_type VALUE 1007,
        aggregate                TYPE ty_expression_type VALUE 1008,
        address                  TYPE ty_expression_type VALUE 1009,
        amordegrc                TYPE ty_expression_type VALUE 1010,
        amorlinc                 TYPE ty_expression_type VALUE 1011,
        and                      TYPE ty_expression_type VALUE 1012,
        arabic                   TYPE ty_expression_type VALUE 1013,
        areas                    TYPE ty_expression_type VALUE 1014,
        arraytotext              TYPE ty_expression_type VALUE 1015,
        asc                      TYPE ty_expression_type VALUE 1016,
        asin                     TYPE ty_expression_type VALUE 1017,
        asinh                    TYPE ty_expression_type VALUE 1018,
        atan                     TYPE ty_expression_type VALUE 1019,
        atan2                    TYPE ty_expression_type VALUE 1020,
        atanh                    TYPE ty_expression_type VALUE 1021,
        avedev                   TYPE ty_expression_type VALUE 1022,
        average                  TYPE ty_expression_type VALUE 1023,
        averagea                 TYPE ty_expression_type VALUE 1024,
        averageif                TYPE ty_expression_type VALUE 1025,
        averageifs               TYPE ty_expression_type VALUE 1026,
        bahttext                 TYPE ty_expression_type VALUE 1027,
        base                     TYPE ty_expression_type VALUE 1028,
        besseli                  TYPE ty_expression_type VALUE 1029,
        besselj                  TYPE ty_expression_type VALUE 1030,
        besselk                  TYPE ty_expression_type VALUE 1031,
        bessely                  TYPE ty_expression_type VALUE 1032,
        betadist                 TYPE ty_expression_type VALUE 1033,
        beta_dist                TYPE ty_expression_type VALUE 1034,
        betainv                  TYPE ty_expression_type VALUE 1035,
        beta_inv                 TYPE ty_expression_type VALUE 1036,
        bin2dec                  TYPE ty_expression_type VALUE 1037,
        bin2hex                  TYPE ty_expression_type VALUE 1038,
        bin2oct                  TYPE ty_expression_type VALUE 1039,
        binomdist                TYPE ty_expression_type VALUE 1040,
        binom_dist               TYPE ty_expression_type VALUE 1041,
        binom_dist_range         TYPE ty_expression_type VALUE 1042,
        binom_inv                TYPE ty_expression_type VALUE 1043,
        bitand                   TYPE ty_expression_type VALUE 1044,
        bitlshift                TYPE ty_expression_type VALUE 1045,
        bitor                    TYPE ty_expression_type VALUE 1046,
        bitrshift                TYPE ty_expression_type VALUE 1047,
        bitxor                   TYPE ty_expression_type VALUE 1048,
        bycol                    TYPE ty_expression_type VALUE 1049,
        byrow                    TYPE ty_expression_type VALUE 1050,
        call                     TYPE ty_expression_type VALUE 1051,
        ceiling                  TYPE ty_expression_type VALUE 1052,
        ceiling_math             TYPE ty_expression_type VALUE 1053,
        ceiling_precise          TYPE ty_expression_type VALUE 1054,
        cell                     TYPE ty_expression_type VALUE 1055,
        char                     TYPE ty_expression_type VALUE 1056,
        chidist                  TYPE ty_expression_type VALUE 1057,
        chiinv                   TYPE ty_expression_type VALUE 1058,
        chitest                  TYPE ty_expression_type VALUE 1059,
        chisq_dist               TYPE ty_expression_type VALUE 1060,
        chisq_dist_rt            TYPE ty_expression_type VALUE 1061,
        chisq_inv                TYPE ty_expression_type VALUE 1062,
        chisq_inv_rt             TYPE ty_expression_type VALUE 1063,
        chisq_test               TYPE ty_expression_type VALUE 1064,
        choose                   TYPE ty_expression_type VALUE 1065,
        choosecols               TYPE ty_expression_type VALUE 1066,
        chooserows               TYPE ty_expression_type VALUE 1067,
        clean                    TYPE ty_expression_type VALUE 1068,
        code                     TYPE ty_expression_type VALUE 1069,
        column                   TYPE ty_expression_type VALUE 1070,
        columns                  TYPE ty_expression_type VALUE 1071,
        combin                   TYPE ty_expression_type VALUE 1072,
        combina                  TYPE ty_expression_type VALUE 1073,
        complex                  TYPE ty_expression_type VALUE 1074,
        concat                   TYPE ty_expression_type VALUE 1075,
        concatenate              TYPE ty_expression_type VALUE 1076,
        confidence               TYPE ty_expression_type VALUE 1077,
        confidence_norm          TYPE ty_expression_type VALUE 1078,
        confidence_t             TYPE ty_expression_type VALUE 1079,
        convert                  TYPE ty_expression_type VALUE 1080,
        correl                   TYPE ty_expression_type VALUE 1081,
        cos                      TYPE ty_expression_type VALUE 1082,
        cosh                     TYPE ty_expression_type VALUE 1083,
        cot                      TYPE ty_expression_type VALUE 1084,
        coth                     TYPE ty_expression_type VALUE 1085,
        count                    TYPE ty_expression_type VALUE 1086,
        counta                   TYPE ty_expression_type VALUE 1087,
        countblank               TYPE ty_expression_type VALUE 1088,
        countif                  TYPE ty_expression_type VALUE 1089,
        countifs                 TYPE ty_expression_type VALUE 1090,
        coupdaybs                TYPE ty_expression_type VALUE 1091,
        coupdays                 TYPE ty_expression_type VALUE 1092,
        coupdaysnc               TYPE ty_expression_type VALUE 1093,
        coupncd                  TYPE ty_expression_type VALUE 1094,
        coupnum                  TYPE ty_expression_type VALUE 1095,
        couppcd                  TYPE ty_expression_type VALUE 1096,
        covar                    TYPE ty_expression_type VALUE 1097,
        covariance_p             TYPE ty_expression_type VALUE 1098,
        covariance_s             TYPE ty_expression_type VALUE 1099,
        critbinom                TYPE ty_expression_type VALUE 1100,
        csc                      TYPE ty_expression_type VALUE 1101,
        csch                     TYPE ty_expression_type VALUE 1102,
        cubekpimember            TYPE ty_expression_type VALUE 1103,
        cubemember               TYPE ty_expression_type VALUE 1104,
        cubememberproperty       TYPE ty_expression_type VALUE 1105,
        cuberankedmember         TYPE ty_expression_type VALUE 1106,
        cubeset                  TYPE ty_expression_type VALUE 1107,
        cubesetcount             TYPE ty_expression_type VALUE 1108,
        cubevalue                TYPE ty_expression_type VALUE 1109,
        cumipmt                  TYPE ty_expression_type VALUE 1110,
        cumprinc                 TYPE ty_expression_type VALUE 1111,
        date                     TYPE ty_expression_type VALUE 1112,
        datedif                  TYPE ty_expression_type VALUE 1113,
        datevalue                TYPE ty_expression_type VALUE 1114,
        daverage                 TYPE ty_expression_type VALUE 1115,
        day                      TYPE ty_expression_type VALUE 1116,
        days                     TYPE ty_expression_type VALUE 1117,
        days360                  TYPE ty_expression_type VALUE 1118,
        db                       TYPE ty_expression_type VALUE 1119,
        dbcs                     TYPE ty_expression_type VALUE 1120,
        dcount                   TYPE ty_expression_type VALUE 1121,
        dcounta                  TYPE ty_expression_type VALUE 1122,
        ddb                      TYPE ty_expression_type VALUE 1123,
        dec2bin                  TYPE ty_expression_type VALUE 1124,
        dec2hex                  TYPE ty_expression_type VALUE 1125,
        dec2oct                  TYPE ty_expression_type VALUE 1126,
        decimal                  TYPE ty_expression_type VALUE 1127,
        degrees                  TYPE ty_expression_type VALUE 1128,
        delta                    TYPE ty_expression_type VALUE 1129,
        devsq                    TYPE ty_expression_type VALUE 1130,
        dget                     TYPE ty_expression_type VALUE 1131,
        disc                     TYPE ty_expression_type VALUE 1132,
        dmax                     TYPE ty_expression_type VALUE 1133,
        dmin                     TYPE ty_expression_type VALUE 1134,
        dollar                   TYPE ty_expression_type VALUE 1135,
        dollarde                 TYPE ty_expression_type VALUE 1136,
        dollarfr                 TYPE ty_expression_type VALUE 1137,
        dproduct                 TYPE ty_expression_type VALUE 1138,
        drop                     TYPE ty_expression_type VALUE 1139,
        dstdev                   TYPE ty_expression_type VALUE 1140,
        dstdevp                  TYPE ty_expression_type VALUE 1141,
        dsum                     TYPE ty_expression_type VALUE 1142,
        duration                 TYPE ty_expression_type VALUE 1143,
        dvar                     TYPE ty_expression_type VALUE 1144,
        dvarp                    TYPE ty_expression_type VALUE 1145,
        edate                    TYPE ty_expression_type VALUE 1146,
        effect                   TYPE ty_expression_type VALUE 1147,
        encodeurl                TYPE ty_expression_type VALUE 1148,
        eomonth                  TYPE ty_expression_type VALUE 1149,
        erf                      TYPE ty_expression_type VALUE 1150,
        erf_precise              TYPE ty_expression_type VALUE 1151,
        erfc                     TYPE ty_expression_type VALUE 1152,
        erfc_precise             TYPE ty_expression_type VALUE 1153,
        error_type               TYPE ty_expression_type VALUE 1154,
        euroconvert              TYPE ty_expression_type VALUE 1155,
        even                     TYPE ty_expression_type VALUE 1156,
        exact                    TYPE ty_expression_type VALUE 1157,
        exp                      TYPE ty_expression_type VALUE 1158,
        expand                   TYPE ty_expression_type VALUE 1159,
        expon_dist               TYPE ty_expression_type VALUE 1160,
        expondist                TYPE ty_expression_type VALUE 1161,
        fact                     TYPE ty_expression_type VALUE 1162,
        factdouble               TYPE ty_expression_type VALUE 1163,
        false                    TYPE ty_expression_type VALUE 1164,
        f_dist                   TYPE ty_expression_type VALUE 1165,
        fdist                    TYPE ty_expression_type VALUE 1166,
        f_dist_rt                TYPE ty_expression_type VALUE 1167,
        filter                   TYPE ty_expression_type VALUE 1168,
        filterxml                TYPE ty_expression_type VALUE 1169,
        find                     TYPE ty_expression_type VALUE 1170,
        findb                    TYPE ty_expression_type VALUE 1171,
        f_inv                    TYPE ty_expression_type VALUE 1172,
        f_inv_rt                 TYPE ty_expression_type VALUE 1173,
        finv                     TYPE ty_expression_type VALUE 1174,
        fisher                   TYPE ty_expression_type VALUE 1175,
        fisherinv                TYPE ty_expression_type VALUE 1176,
        fixed                    TYPE ty_expression_type VALUE 1177,
        floor                    TYPE ty_expression_type VALUE 1178,
        floor_math               TYPE ty_expression_type VALUE 1179,
        floor_precise            TYPE ty_expression_type VALUE 1180,
        forecast                 TYPE ty_expression_type VALUE 1181,
        forecast_ets             TYPE ty_expression_type VALUE 1182,
        forecast_ets_confint     TYPE ty_expression_type VALUE 1183,
        forecast_ets_seasonality TYPE ty_expression_type VALUE 1184,
        forecast_ets_stat        TYPE ty_expression_type VALUE 1185,
        forecast_linear          TYPE ty_expression_type VALUE 1186,
        formulatext              TYPE ty_expression_type VALUE 1187,
        frequency                TYPE ty_expression_type VALUE 1188,
        f_test                   TYPE ty_expression_type VALUE 1189,
        ftest                    TYPE ty_expression_type VALUE 1190,
        fv                       TYPE ty_expression_type VALUE 1191,
        fvschedule               TYPE ty_expression_type VALUE 1192,
        gamma                    TYPE ty_expression_type VALUE 1193,
        gamma_dist               TYPE ty_expression_type VALUE 1194,
        gammadist                TYPE ty_expression_type VALUE 1195,
        gamma_inv                TYPE ty_expression_type VALUE 1196,
        gammainv                 TYPE ty_expression_type VALUE 1197,
        gammaln                  TYPE ty_expression_type VALUE 1198,
        gammaln_precise          TYPE ty_expression_type VALUE 1199,
        gauss                    TYPE ty_expression_type VALUE 1200,
        gcd                      TYPE ty_expression_type VALUE 1201,
        geomean                  TYPE ty_expression_type VALUE 1202,
        gestep                   TYPE ty_expression_type VALUE 1203,
        getpivotdata             TYPE ty_expression_type VALUE 1204,
        growth                   TYPE ty_expression_type VALUE 1205,
        harmean                  TYPE ty_expression_type VALUE 1206,
        hex2bin                  TYPE ty_expression_type VALUE 1207,
        hex2dec                  TYPE ty_expression_type VALUE 1208,
        hex2oct                  TYPE ty_expression_type VALUE 1209,
        hlookup                  TYPE ty_expression_type VALUE 1210,
        hour                     TYPE ty_expression_type VALUE 1211,
        hstack                   TYPE ty_expression_type VALUE 1212,
        hyperlink                TYPE ty_expression_type VALUE 1213,
        hypgeom_dist             TYPE ty_expression_type VALUE 1214,
        hypgeomdist              TYPE ty_expression_type VALUE 1215,
        if                       TYPE ty_expression_type VALUE 1216,
        iferror                  TYPE ty_expression_type VALUE 1217,
        ifna                     TYPE ty_expression_type VALUE 1218,
        ifs                      TYPE ty_expression_type VALUE 1219,
        imabs                    TYPE ty_expression_type VALUE 1220,
        image                    TYPE ty_expression_type VALUE 1221,
        imaginary                TYPE ty_expression_type VALUE 1222,
        imargument               TYPE ty_expression_type VALUE 1223,
        imconjugate              TYPE ty_expression_type VALUE 1224,
        imcos                    TYPE ty_expression_type VALUE 1225,
        imcosh                   TYPE ty_expression_type VALUE 1226,
        imcot                    TYPE ty_expression_type VALUE 1227,
        imcsc                    TYPE ty_expression_type VALUE 1228,
        imcsch                   TYPE ty_expression_type VALUE 1229,
        imdiv                    TYPE ty_expression_type VALUE 1230,
        imexp                    TYPE ty_expression_type VALUE 1231,
        imln                     TYPE ty_expression_type VALUE 1232,
        imlog10                  TYPE ty_expression_type VALUE 1233,
        imlog2                   TYPE ty_expression_type VALUE 1234,
        impower                  TYPE ty_expression_type VALUE 1235,
        improduct                TYPE ty_expression_type VALUE 1236,
        imreal                   TYPE ty_expression_type VALUE 1237,
        imsec                    TYPE ty_expression_type VALUE 1238,
        imsech                   TYPE ty_expression_type VALUE 1239,
        imsin                    TYPE ty_expression_type VALUE 1240,
        imsinh                   TYPE ty_expression_type VALUE 1241,
        imsqrt                   TYPE ty_expression_type VALUE 1242,
        imsub                    TYPE ty_expression_type VALUE 1243,
        imsum                    TYPE ty_expression_type VALUE 1244,
        imtan                    TYPE ty_expression_type VALUE 1245,
        index                    TYPE ty_expression_type VALUE 1246,
        indirect                 TYPE ty_expression_type VALUE 1247,
        info                     TYPE ty_expression_type VALUE 1248,
        int                      TYPE ty_expression_type VALUE 1249,
        intercept                TYPE ty_expression_type VALUE 1250,
        intrate                  TYPE ty_expression_type VALUE 1251,
        ipmt                     TYPE ty_expression_type VALUE 1252,
        irr                      TYPE ty_expression_type VALUE 1253,
        isblank                  TYPE ty_expression_type VALUE 1254,
        iserr                    TYPE ty_expression_type VALUE 1255,
        iserror                  TYPE ty_expression_type VALUE 1256,
        iseven                   TYPE ty_expression_type VALUE 1257,
        isformula                TYPE ty_expression_type VALUE 1258,
        islogical                TYPE ty_expression_type VALUE 1259,
        isna                     TYPE ty_expression_type VALUE 1260,
        isnontext                TYPE ty_expression_type VALUE 1261,
        isnumber                 TYPE ty_expression_type VALUE 1262,
        isodd                    TYPE ty_expression_type VALUE 1263,
        isomitted                TYPE ty_expression_type VALUE 1264,
        isref                    TYPE ty_expression_type VALUE 1265,
        istext                   TYPE ty_expression_type VALUE 1266,
        iso_ceiling              TYPE ty_expression_type VALUE 1267,
        isoweeknum               TYPE ty_expression_type VALUE 1268,
        ispmt                    TYPE ty_expression_type VALUE 1269,
        jis                      TYPE ty_expression_type VALUE 1270,
        kurt                     TYPE ty_expression_type VALUE 1271,
        lambda                   TYPE ty_expression_type VALUE 1272,
        large                    TYPE ty_expression_type VALUE 1273,
        lcm                      TYPE ty_expression_type VALUE 1274,
        left                     TYPE ty_expression_type VALUE 1275,
        leftb                    TYPE ty_expression_type VALUE 1276,
        len                      TYPE ty_expression_type VALUE 1277,
        lenb                     TYPE ty_expression_type VALUE 1278,
        let                      TYPE ty_expression_type VALUE 1279,
        linest                   TYPE ty_expression_type VALUE 1280,
        ln                       TYPE ty_expression_type VALUE 1281,
        log                      TYPE ty_expression_type VALUE 1282,
        log10                    TYPE ty_expression_type VALUE 1283,
        logest                   TYPE ty_expression_type VALUE 1284,
        loginv                   TYPE ty_expression_type VALUE 1285,
        lognorm_dist             TYPE ty_expression_type VALUE 1286,
        lognormdist              TYPE ty_expression_type VALUE 1287,
        lognorm_inv              TYPE ty_expression_type VALUE 1288,
        lookup                   TYPE ty_expression_type VALUE 1289,
        lower                    TYPE ty_expression_type VALUE 1290,
        makearray                TYPE ty_expression_type VALUE 1291,
        map                      TYPE ty_expression_type VALUE 1292,
        match                    TYPE ty_expression_type VALUE 1293,
        max                      TYPE ty_expression_type VALUE 1294,
        maxa                     TYPE ty_expression_type VALUE 1295,
        maxifs                   TYPE ty_expression_type VALUE 1296,
        mdeterm                  TYPE ty_expression_type VALUE 1297,
        mduration                TYPE ty_expression_type VALUE 1298,
        median                   TYPE ty_expression_type VALUE 1299,
        mid                      TYPE ty_expression_type VALUE 1300,
        midb                     TYPE ty_expression_type VALUE 1301,
        min                      TYPE ty_expression_type VALUE 1302,
        minifs                   TYPE ty_expression_type VALUE 1303,
        mina                     TYPE ty_expression_type VALUE 1304,
        minute                   TYPE ty_expression_type VALUE 1305,
        minverse                 TYPE ty_expression_type VALUE 1306,
        mirr                     TYPE ty_expression_type VALUE 1307,
        mmult                    TYPE ty_expression_type VALUE 1308,
        mod                      TYPE ty_expression_type VALUE 1309,
        mode                     TYPE ty_expression_type VALUE 1310,
        mode_mult                TYPE ty_expression_type VALUE 1311,
        mode_sngl                TYPE ty_expression_type VALUE 1312,
        month                    TYPE ty_expression_type VALUE 1313,
        mround                   TYPE ty_expression_type VALUE 1314,
        multinomial              TYPE ty_expression_type VALUE 1315,
        munit                    TYPE ty_expression_type VALUE 1316,
        n                        TYPE ty_expression_type VALUE 1317,
        na                       TYPE ty_expression_type VALUE 1318,
        negbinom_dist            TYPE ty_expression_type VALUE 1319,
        negbinomdist             TYPE ty_expression_type VALUE 1320,
        networkdays              TYPE ty_expression_type VALUE 1321,
        networkdays_intl         TYPE ty_expression_type VALUE 1322,
        nominal                  TYPE ty_expression_type VALUE 1323,
        norm_dist                TYPE ty_expression_type VALUE 1324,
        normdist                 TYPE ty_expression_type VALUE 1325,
        norminv                  TYPE ty_expression_type VALUE 1326,
        norm_inv                 TYPE ty_expression_type VALUE 1327,
        norm_s_dist              TYPE ty_expression_type VALUE 1328,
        normsdist                TYPE ty_expression_type VALUE 1329,
        norm_s_inv               TYPE ty_expression_type VALUE 1330,
        normsinv                 TYPE ty_expression_type VALUE 1331,
        not                      TYPE ty_expression_type VALUE 1332,
        now                      TYPE ty_expression_type VALUE 1333,
        nper                     TYPE ty_expression_type VALUE 1334,
        npv                      TYPE ty_expression_type VALUE 1335,
        numbervalue              TYPE ty_expression_type VALUE 1336,
        oct2bin                  TYPE ty_expression_type VALUE 1337,
        oct2dec                  TYPE ty_expression_type VALUE 1338,
        oct2hex                  TYPE ty_expression_type VALUE 1339,
        odd                      TYPE ty_expression_type VALUE 1340,
        oddfprice                TYPE ty_expression_type VALUE 1341,
        oddfyield                TYPE ty_expression_type VALUE 1342,
        oddlprice                TYPE ty_expression_type VALUE 1343,
        oddlyield                TYPE ty_expression_type VALUE 1344,
        offset                   TYPE ty_expression_type VALUE 1345,
        or                       TYPE ty_expression_type VALUE 1346,
        pduration                TYPE ty_expression_type VALUE 1347,
        pearson                  TYPE ty_expression_type VALUE 1348,
        percentile_exc           TYPE ty_expression_type VALUE 1349,
        percentile_inc           TYPE ty_expression_type VALUE 1350,
        percentile               TYPE ty_expression_type VALUE 1351,
        percentrank_exc          TYPE ty_expression_type VALUE 1352,
        percentrank_inc          TYPE ty_expression_type VALUE 1353,
        percentrank              TYPE ty_expression_type VALUE 1354,
        permut                   TYPE ty_expression_type VALUE 1355,
        permutationa             TYPE ty_expression_type VALUE 1356,
        phi                      TYPE ty_expression_type VALUE 1357,
        phonetic                 TYPE ty_expression_type VALUE 1358,
        pi                       TYPE ty_expression_type VALUE 1359,
        pmt                      TYPE ty_expression_type VALUE 1360,
        poisson_dist             TYPE ty_expression_type VALUE 1361,
        poisson                  TYPE ty_expression_type VALUE 1362,
        power                    TYPE ty_expression_type VALUE 1363,
        ppmt                     TYPE ty_expression_type VALUE 1364,
        price                    TYPE ty_expression_type VALUE 1365,
        pricedisc                TYPE ty_expression_type VALUE 1366,
        pricemat                 TYPE ty_expression_type VALUE 1367,
        prob                     TYPE ty_expression_type VALUE 1368,
        product                  TYPE ty_expression_type VALUE 1369,
        proper                   TYPE ty_expression_type VALUE 1370,
        pv                       TYPE ty_expression_type VALUE 1371,
        quartile                 TYPE ty_expression_type VALUE 1372,
        quartile_exc             TYPE ty_expression_type VALUE 1373,
        quartile_inc             TYPE ty_expression_type VALUE 1374,
        quotient                 TYPE ty_expression_type VALUE 1375,
        radians                  TYPE ty_expression_type VALUE 1376,
        rand                     TYPE ty_expression_type VALUE 1377,
        randarray                TYPE ty_expression_type VALUE 1378,
        randbetween              TYPE ty_expression_type VALUE 1379,
        rank_avg                 TYPE ty_expression_type VALUE 1380,
        rank_eq                  TYPE ty_expression_type VALUE 1381,
        rank                     TYPE ty_expression_type VALUE 1382,
        rate                     TYPE ty_expression_type VALUE 1383,
        received                 TYPE ty_expression_type VALUE 1384,
        reduce                   TYPE ty_expression_type VALUE 1385,
        register_id              TYPE ty_expression_type VALUE 1386,
        replace                  TYPE ty_expression_type VALUE 1387,
        replaceb                 TYPE ty_expression_type VALUE 1388,
        rept                     TYPE ty_expression_type VALUE 1389,
        right                    TYPE ty_expression_type VALUE 1390,
        rightb                   TYPE ty_expression_type VALUE 1391,
        roman                    TYPE ty_expression_type VALUE 1392,
        round                    TYPE ty_expression_type VALUE 1393,
        rounddown                TYPE ty_expression_type VALUE 1394,
        roundup                  TYPE ty_expression_type VALUE 1395,
        row                      TYPE ty_expression_type VALUE 1396,
        rows                     TYPE ty_expression_type VALUE 1397,
        rri                      TYPE ty_expression_type VALUE 1398,
        rsq                      TYPE ty_expression_type VALUE 1399,
        rtd                      TYPE ty_expression_type VALUE 1400,
        scan                     TYPE ty_expression_type VALUE 1401,
        search                   TYPE ty_expression_type VALUE 1402,
        searchb                  TYPE ty_expression_type VALUE 1403,
        sec                      TYPE ty_expression_type VALUE 1404,
        sech                     TYPE ty_expression_type VALUE 1405,
        second                   TYPE ty_expression_type VALUE 1406,
        sequence                 TYPE ty_expression_type VALUE 1407,
        seriessum                TYPE ty_expression_type VALUE 1408,
        sheet                    TYPE ty_expression_type VALUE 1409,
        sheets                   TYPE ty_expression_type VALUE 1410,
        sign                     TYPE ty_expression_type VALUE 1411,
        sin                      TYPE ty_expression_type VALUE 1412,
        sinh                     TYPE ty_expression_type VALUE 1413,
        skew                     TYPE ty_expression_type VALUE 1414,
        skew_p                   TYPE ty_expression_type VALUE 1415,
        sln                      TYPE ty_expression_type VALUE 1416,
        slope                    TYPE ty_expression_type VALUE 1417,
        small                    TYPE ty_expression_type VALUE 1418,
        sort                     TYPE ty_expression_type VALUE 1419,
        sortby                   TYPE ty_expression_type VALUE 1420,
        sqrt                     TYPE ty_expression_type VALUE 1421,
        sqrtpi                   TYPE ty_expression_type VALUE 1422,
        standardize              TYPE ty_expression_type VALUE 1423,
        stockhistory             TYPE ty_expression_type VALUE 1424,
        stdev                    TYPE ty_expression_type VALUE 1425,
        stdev_p                  TYPE ty_expression_type VALUE 1426,
        stdev_s                  TYPE ty_expression_type VALUE 1427,
        stdeva                   TYPE ty_expression_type VALUE 1428,
        stdevp                   TYPE ty_expression_type VALUE 1429,
        stdevpa                  TYPE ty_expression_type VALUE 1430,
        steyx                    TYPE ty_expression_type VALUE 1431,
        substitute               TYPE ty_expression_type VALUE 1432,
        subtotal                 TYPE ty_expression_type VALUE 1433,
        sum                      TYPE ty_expression_type VALUE 1434,
        sumif                    TYPE ty_expression_type VALUE 1435,
        sumifs                   TYPE ty_expression_type VALUE 1436,
        sumproduct               TYPE ty_expression_type VALUE 1437,
        sumsq                    TYPE ty_expression_type VALUE 1438,
        sumx2my2                 TYPE ty_expression_type VALUE 1439,
        sumx2py2                 TYPE ty_expression_type VALUE 1440,
        sumxmy2                  TYPE ty_expression_type VALUE 1441,
        switch                   TYPE ty_expression_type VALUE 1442,
        syd                      TYPE ty_expression_type VALUE 1443,
        t                        TYPE ty_expression_type VALUE 1444,
        tan                      TYPE ty_expression_type VALUE 1445,
        tanh                     TYPE ty_expression_type VALUE 1446,
        take                     TYPE ty_expression_type VALUE 1447,
        tbilleq                  TYPE ty_expression_type VALUE 1448,
        tbillprice               TYPE ty_expression_type VALUE 1449,
        tbillyield               TYPE ty_expression_type VALUE 1450,
        t_dist                   TYPE ty_expression_type VALUE 1451,
        t_dist_2t                TYPE ty_expression_type VALUE 1452,
        t_dist_rt                TYPE ty_expression_type VALUE 1453,
        tdist                    TYPE ty_expression_type VALUE 1454,
        text                     TYPE ty_expression_type VALUE 1455,
        textafter                TYPE ty_expression_type VALUE 1456,
        textbefore               TYPE ty_expression_type VALUE 1457,
        textjoin                 TYPE ty_expression_type VALUE 1458,
        textsplit                TYPE ty_expression_type VALUE 1459,
        time                     TYPE ty_expression_type VALUE 1460,
        timevalue                TYPE ty_expression_type VALUE 1461,
        t_inv                    TYPE ty_expression_type VALUE 1462,
        t_inv_2t                 TYPE ty_expression_type VALUE 1463,
        tinv                     TYPE ty_expression_type VALUE 1464,
        tocol                    TYPE ty_expression_type VALUE 1465,
        torow                    TYPE ty_expression_type VALUE 1466,
        today                    TYPE ty_expression_type VALUE 1467,
        transpose                TYPE ty_expression_type VALUE 1468,
        trend                    TYPE ty_expression_type VALUE 1469,
        trim                     TYPE ty_expression_type VALUE 1470,
        trimmean                 TYPE ty_expression_type VALUE 1471,
        true                     TYPE ty_expression_type VALUE 1472,
        trunc                    TYPE ty_expression_type VALUE 1473,
        t_test                   TYPE ty_expression_type VALUE 1474,
        ttest                    TYPE ty_expression_type VALUE 1475,
        type                     TYPE ty_expression_type VALUE 1476,
        unichar                  TYPE ty_expression_type VALUE 1477,
        unicode                  TYPE ty_expression_type VALUE 1478,
        unique                   TYPE ty_expression_type VALUE 1479,
        upper                    TYPE ty_expression_type VALUE 1480,
        value                    TYPE ty_expression_type VALUE 1481,
        valuetotext              TYPE ty_expression_type VALUE 1482,
        var                      TYPE ty_expression_type VALUE 1483,
        var_p                    TYPE ty_expression_type VALUE 1484,
        var_s                    TYPE ty_expression_type VALUE 1485,
        vara                     TYPE ty_expression_type VALUE 1486,
        varp                     TYPE ty_expression_type VALUE 1487,
        varpa                    TYPE ty_expression_type VALUE 1488,
        vdb                      TYPE ty_expression_type VALUE 1489,
        vlookup                  TYPE ty_expression_type VALUE 1490,
        vstack                   TYPE ty_expression_type VALUE 1491,
        webservice               TYPE ty_expression_type VALUE 1492,
        weekday                  TYPE ty_expression_type VALUE 1493,
        weeknum                  TYPE ty_expression_type VALUE 1494,
        weibull                  TYPE ty_expression_type VALUE 1495,
        weibull_dist             TYPE ty_expression_type VALUE 1496,
        workday                  TYPE ty_expression_type VALUE 1497,
        workday_intl             TYPE ty_expression_type VALUE 1498,
        wrapcols                 TYPE ty_expression_type VALUE 1499,
        wraprows                 TYPE ty_expression_type VALUE 1500,
        xirr                     TYPE ty_expression_type VALUE 1501,
        xlookup                  TYPE ty_expression_type VALUE 1502,
        xmatch                   TYPE ty_expression_type VALUE 1503,
        xnpv                     TYPE ty_expression_type VALUE 1504,
        xor                      TYPE ty_expression_type VALUE 1505,
        year                     TYPE ty_expression_type VALUE 1506,
        yearfrac                 TYPE ty_expression_type VALUE 1507,
        yield                    TYPE ty_expression_type VALUE 1508,
        yielddisc                TYPE ty_expression_type VALUE 1509,
        yieldmat                 TYPE ty_expression_type VALUE 1510,
        z_test                   TYPE ty_expression_type VALUE 1511,
        ztest                    TYPE ty_expression_type VALUE 1512,
      END OF function,
    END OF c_type.

  DATA type                  TYPE ty_expression_type     READ-ONLY.
  DATA result_of_evaluation  TYPE REF TO zif_xlom__va    READ-ONLY.
  DATA parameters            TYPE tt_parameter           READ-ONLY.
  DATA arguments_or_operands TYPE tt_argument_or_operand READ-ONLY.
*  DATA arguments_or_operands TYPE tt_argument_or_operand READ-ONLY.

*  METHODS evaluate
*    IMPORTING !context      TYPE REF TO zcl_xlom__ex_ut_eval_context
*    RETURNING VALUE(result) TYPE REF TO zif_xlom__va.

  METHODS evaluate_single
    IMPORTING arguments     TYPE tt_operand_result
              !context      TYPE REF TO zcl_xlom__ex_ut_eval_context
    RETURNING VALUE(result) TYPE REF TO zif_xlom__va.

*  "! Compare two expressions. NB: this other method may also be used ZCL_XLOM__EX_UT=>ARE_EQUAL( expression_1 = ... expression_2 = ... ).
*  METHODS is_equal
*    IMPORTING expression    TYPE REF TO zif_xlom__ex
*    RETURNING VALUE(result) TYPE abap_bool.
*
*  METHODS set_arguments_or_operands
*    IMPORTING arguments_or_operands TYPE tt_argument_or_operand.
*
*  METHODS set_result
*    IMPORTING !value        TYPE REF TO zif_xlom__va
*    RETURNING VALUE(result) TYPE REF TO zif_xlom__va.
ENDINTERFACE.
